[package]
name = "node-rs"
version = "0.1.0"
authors = ["SecMeant <secmeant@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0"
protobuf = "2"

[build-dependencies]
protoc-rust = "2.0"
